// flow-typed signature: ea6597df2a32ed4a07af295665ab8036
// flow-typed version: <<STUB>>/gatsby-plugin-stylelint_v^3.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "gatsby-plugin-stylelint" {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "gatsby-plugin-stylelint/gatsby-node" {
    declare module.exports: any;
}

// Filename aliases
declare module "gatsby-plugin-stylelint/gatsby-node.js" {
    declare module.exports: $Exports<"gatsby-plugin-stylelint/gatsby-node">;
}
declare module "gatsby-plugin-stylelint/index" {
    declare module.exports: $Exports<"gatsby-plugin-stylelint">;
}
declare module "gatsby-plugin-stylelint/index.js" {
    declare module.exports: $Exports<"gatsby-plugin-stylelint">;
}
